name: coursera
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipykernel
  - nb_conda
  - jupyter_contrib_nbextensions
  - nbdime
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - scikit-learn
  - yapf
  - isort
  - html5lib
  - beautifulsoup4
  - folium
